### ISSUE TITLE
API-Manager POD constantly reports: logged Failure at ... with log description: Filter failed

### ISSUE THREAD

**Issue by dokuboyejo** [Axway/Cloud-Automation#27]
Hi,

On  a new api manager deployed to k8s, two issues were encountered

- login failure using default credential
- continuous filter failure
```
ERROR   22/Feb/2022:13:57:12.010 [0050:b8eb14620700bf3380c61140] The message [Id-b8eb14620700bf3380c61140] logged Failure at 02.22.2022 13:57:12,010 with log description: Filter failed
ERROR   22/Feb/2022:13:57:17.012 [0052:bdeb146208001d747ff5a5a3] The message [Id-bdeb146208001d747ff5a5a3] logged Failure at 02.22.2022 13:57:17,012 with log description: Filter failed
ERROR   22/Feb/2022:13:57:18.396 [004c:beeb14620900d7ce99d9e0e6] The message [Id-beeb14620900d7ce99d9e0e6] logged Failure at 02.22.2022 13:57:18,395 with log description: Filter failed
ERROR   22/Feb/2022:13:57:18.399 [0052:beeb14620a005cd015475b2e] The message [Id-beeb14620a005cd015475b2e] logged Failure at 02.22.2022 13:57:18,399 with log description: Filter failed
ERROR   22/Feb/2022:13:57:18.410 [004d:beeb14620b00b40b9c38b8bb] The message [Id-beeb14620b00b40b9c38b8bb] logged Failure at 02.22.2022 13:57:18,410 with log description: Filter failed
```

**Comment by cwiechmann** [comment]
To be sure: API-Manager or API-Gateway Manager?

**Comment by cwiechmann** [comment]
Okay, but is it for API-Manager (apimgr) or API-Gateway-Manager (anm) ?

**Comment by cwiechmann** [comment]
This is because there is not healthcheck endpoint for the API-Manager that could be used to verify readiness & healthiness. For that reason, it just pings the API-Manager on the root:
```yaml
   livenessProbe:
      httpGet:
         path: /
         port: manager
         httpHeaders:
         - name: k8sprobe
           value: liveness.apimgr
         scheme: HTTPS
      initialDelaySeconds: 300
      periodSeconds: 30
      timeoutSeconds: 15
      failureThreshold: 3
      successThreshold: 1
```

As you may know, this turns into the policy: `API Manager Protection Policy` handling this request. Unfortunately, by default one of the filters in this policy is logging this error:
![image](https://user-images.githubusercontent.com/16292002/155159826-006747ad-ad8c-4b47-967b-dfa369391cb7.png)

So, my recommendation is to change this filter and disable the error reporting as it's useless:
![image](https://user-images.githubusercontent.com/16292002/155160010-a2182880-baf8-4900-9775-0ae63ce9a9d5.png)

Alternatively if you find a better way to verify the API-Manager is running, please let me know.

**Comment by cwiechmann** [comment]
I raised this point at Axway R&D to get this Error-Logging disabled by default. For now, you can change this yourself.
