### ISSUE TITLE
issues when creating cassandra schema

### ISSUE THREAD

**Issue by jacinml** [Axway/Cloud-Automation#29]
I got errors on the first deployment using the helms v 2.7.0 on the apimgr and traffic nodes.
The issues are due to errors when creating the db schema in cassandra.
How feasible would be to add an init-container in the traffic pod for waiting until the apimgr is fully up?  In that way they would not try to add/access the same cassandra resources.

see one of the errors that are triggered:

ERROR   07/Mar/2022:16:59:47.844 [0001:000000000000000000000000]     Schema check failed for store: [API Portal_ApiAppPolicyBindings, API Portal_ApiOrgPolicyBindings, API Portal_ApiPolicyParameters, API Portal_PortalAPI, API Portal_PortalAPIMethod, API Portal_PortalActionQueue, API Portal_PortalApiAccessStore, API Portal_PortalApiQuotaConstraintStore, API Portal_PortalApiQuotaDetailsStore, API Portal_PortalApiQuotaStore, API Portal_PortalApplicationPermissionStore, API Portal_PortalConfigStore, API Portal_PortalExports, API Portal_PortalIdentityStore, API Portal_PortalOrganizationStore, API Portal_PortalOrganizationStoreLDAP, API Portal_PortalRegistrationToken, API Portal_PortalRemoteHost, API Portal_PortalTimestamp, API Portal_PortalUserStore, API Portal_PortalUserStoreLDAP, API Portal_PortalVirtualizedAPI, API Portal_PortalVirtualizedAPIMethod, API Server_PortalApiKeyStore, API Server_PortalApplicationStore, API Server_PortalExternalClientStore, API Server_PortalOAuthResourcesStore, API Server_PortalOAuthStore, OAuth_AccessTokens, OAuth_AuthZCodes, OAuth_Authorizations, OAuth_ClientAccessTokens, OAuth_ClientRefreshTokens, OAuth_RefreshTokens]: 
com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table kps_schema

Thank you.

**Comment by cwiechmann** [comment]
Hmm, at least in my environment, I deploy the API-Manager and API-Traffic quite often together, as they are based on the same docker-image. 
With that dependency, it would extend (more of less double) the deployment cycle, as the API-Traffic-PODs would have to wait for the API-Manager to be fully up and running. That's why I don't like that idea. 

One option would be to manually check the Cassandra-DB in an Init-Container using CQL Shell. However, this issue appears exactly once on the very first deployment. I think it's acceptable to have 1 POD restart due to this.

**Comment by cwiechmann** [comment]
I'm going to close this issue now, for this reason:

> However, this issue appears exactly once on the very first deployment. I think it's acceptable to have 1 POD restart due to this.

If you don't agree @jacinml, please re-open this issue.
